// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsxoha8WSDQguNFw4TOETWW2cKTl7uRjc',
    appId: '1:849040960929:web:21741e3468223f5b346fe0',
    messagingSenderId: '849040960929',
    projectId: 'unilost-5e04e',
    authDomain: 'unilost-5e04e.firebaseapp.com',
    storageBucket: 'unilost-5e04e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQHs4z5UVtawdIe3-ud4pehLZ4mK-NPCE',
    appId: '1:849040960929:android:e170b59ee11cac9d346fe0',
    messagingSenderId: '849040960929',
    projectId: 'unilost-5e04e',
    storageBucket: 'unilost-5e04e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwPmObOPgPaH2rfEV8rxWi3f08c4CURnM',
    appId: '1:849040960929:ios:6c21849ef62889f9346fe0',
    messagingSenderId: '849040960929',
    projectId: 'unilost-5e04e',
    storageBucket: 'unilost-5e04e.firebasestorage.app',
    iosBundleId: 'com.unilost.unilost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwPmObOPgPaH2rfEV8rxWi3f08c4CURnM',
    appId: '1:849040960929:ios:6c21849ef62889f9346fe0',
    messagingSenderId: '849040960929',
    projectId: 'unilost-5e04e',
    storageBucket: 'unilost-5e04e.firebasestorage.app',
    iosBundleId: 'com.unilost.unilost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsxoha8WSDQguNFw4TOETWW2cKTl7uRjc',
    appId: '1:849040960929:web:673018ad060596dc346fe0',
    messagingSenderId: '849040960929',
    projectId: 'unilost-5e04e',
    authDomain: 'unilost-5e04e.firebaseapp.com',
    storageBucket: 'unilost-5e04e.firebasestorage.app',
  );
}
